version: "3.3"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    depends_on:
    - traefik
    env_file: .env
    volumes:
    - /config/jackett:/config
    - /media/downloads:/downloads
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:jackett.${DOMAIN}
    - traefik.port=9117
  plex:
    image: plexinc/pms-docker
    container_name: plex
    depends_on:
    - traefik
    env_file: .env
    network_mode: host
    devices:
    - /dev/dri:/dev/dri
    hostname: watchtower.${DOMAIN}
    volumes:
    - /config/plex:/config
    - /var/lib/plex/data:/data
    - /var/lib/plex/transcode:/transcode
    - /media/movies:/data/movies
    - /media/shows:/data/tvshows
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:watchtower.${DOMAIN}
    - traefik.port=32400
  portainer:
    image: portainer/portainer
    container_name: portainer
    depends_on:
    - traefik
    env_file: .env
    command: -H unix:///var/run/docker.sock
    volumes:
    - /config/portainer/data:/data
    - /config/shared:/shared
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:portainer.${DOMAIN}
    - traefik.port=9000
  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbt
    privileged: true
    depends_on:
    - traefik
    env_file: .env
    environment:
    - LAN_NETWORK=192.168.1.0/24
    - NAME_SERVERS=1.1.1.1,1.0.0.1
    - VPN_ENABLED=yes
    - WEBUI_PORT_ENV=8181
    ports:
    - 8181:8181
    - 8999:8999/tcp
    - 8999:8999/udp
    expose:
    - 8181
    volumes:
    - /config/qbt:/config
    - /media/downloads:/downloads
    - /media:/media
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:qbt.${DOMAIN}
    - traefik.port=8181
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
    - jackett
    - qbittorrentvpn
    - traefik
    env_file: .env
    volumes:
    - /config/radarr:/config
    - /media/movies:/movies
    - /media/downloads:/downloads
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:radarr.${DOMAIN}
    - traefik.port=7878
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
    - jackett
    - qbittorrentvpn
    - traefik
    env_file: .env
    volumes:
    - /config/sonarr:/config
    - /media/downloads:/downloads
    - /media/shows:/tv
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:sonarr.${DOMAIN}
    - traefik.port=8989
  traefik:
    image: traefik:1.7.16
    container_name: traefik
    env_file: .env
    network_mode: host
    ports:
    - 80:80
    - 443:443
    expose:
    - 8080
    command: --web
    volumes:
    - /config/traefik/fullchain.pem:/cert.pem
    - /config/traefik/privkey.pem:/privkey.pem
    - ./traefik/traefik.toml:/traefik.toml
    - ./traefik/.htpasswd:/.htpasswd
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:traefik.${DOMAIN}
    - traefik.port=8080
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "1000"
    depends_on:
    - cadvisor
    - traefik
    env_file: .env
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - /config/prometheus:/prometheus
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:prometheus.${DOMAIN}
    - traefik.port=9090
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    env_file: .env
    command: --port 9999
    ports:
    - 9999:9999
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "1000"
    depends_on:
    - prometheus
    - traefik
    env_file: .env
    ports:
    - 3000:3000
    volumes:
    - /config/grafana:/var/lib/grafana
    - ./grafana/provisioning/:/etc/grafana/provisioning/
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:grafana.${DOMAIN}
    - traefik.port=3000
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    env_file: .env
    ports:
    - 9100:9100
    command:
    - --path.procfs=/host/proc
    - --path.sysfs=/host/sys
    - --collector.filesystem.ignored-mount-points
    - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    env_file: .env
    ports:
    - 9093:9093
