version: "3.3"
services:
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
    - 9093:9093
    env_file: .env
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    ports:
    - 9999:9999
    env_file: .env
    command: --port 9999
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
    - prometheus
    - traefik
    user: ${PUID}
    volumes:
    - ${CONFIG_PATH}/grafana:/var/lib/grafana
    - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
    - 3000:3000
    env_file: .env
    environment:
    - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel
    labels:
    - traefik.enable=true
    - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)
    - traefik.http.routers.grafana.entrypoints=websecure
    - traefik.http.routers.grafana.tls.certresolver=mydnschallenge
    - traefik.http.services.grafana.loadbalancer.server.port=3000
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
    - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    - ${CONFIG_PATH}/influxdb/db:/var/lib/influxdb
    ports:
    - 8086:8086
    - 8089:8089/udp
    env_file: .env
    environment:
    - INFLUXDB_HTTP_ENABLED=true
    - INFLUXDB_DB=host
    command: -config /etc/influxdb/influxdb.conf
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    depends_on:
    - traefik
    volumes:
    - ${CONFIG_PATH}/jackett:/config
    - ${DL_PATH}:/downloads
    ports:
    - 9117:9117/tcp
    env_file: .env
    labels:
    - traefik.enable=true
    - traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN}`)
    - traefik.http.routers.jackett.entrypoints=websecure
    - traefik.http.routers.jackett.tls.certresolver=mydnschallenge
    - traefik.http.services.jackett.loadbalancer.server.port=9117
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    depends_on:
    - traefik
    volumes:
    - ${CONFIG_PATH}/lidarr:/config
    - ${DL_PATH}:/downloads
    - ${MEDIA_PATH}/music:/music
    ports:
    - 8686:8686
    env_file: .env
    labels:
    - traefik.enable=true
    - traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN}`)
    - traefik.http.routers.lidarr.entrypoints=websecure
    - traefik.http.routers.lidarr.tls.certresolver=mydnschallenge
    - traefik.http.services.lidarr.loadbalancer.server.port=8686
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    privileged: true
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    ports:
    - 9100:9100
    env_file: .env
    command:
    - --path.procfs=/host/proc
    - --path.sysfs=/host/sys
    - --collector.filesystem.ignored-mount-points
    - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
  plex:
    image: plexinc/pms-docker
    container_name: plex
    depends_on:
    - traefik
    devices:
    - /dev/dri:/dev/dri
    volumes:
    - ${CONFIG_PATH}/plex:/config
    - /var/lib/plex/data:/data
    - /var/lib/plex/transcode:/transcode
    - ${MEDIA_PATH}/movies:/data/movies
    - ${MEDIA_PATH}/shows:/data/tvshows
    hostname: watchtower.${DOMAIN}
    ports:
    - 1900:1900/udp
    - 3005:3005/tcp
    - 8324:8324/tcp
    - 32400:32400/tcp
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
    - 32469:32469/tcp
    env_file: .env
    environment:
    - PLEX_CLAIM=${CLAIM}
    - ADVERTISE_IP="https://watchtower.${DOMAIN}"
    labels:
    - traefik.enable=true
    - traefik.http.routers.plex.rule=Host(`watchtower.${DOMAIN}`)
    - traefik.http.routers.plex.entrypoints=websecure
    - traefik.http.routers.plex.tls.certresolver=mydnschallenge
    - traefik.http.services.plex.loadbalancer.server.port=32400
  portainer:
    image: portainer/portainer
    container_name: portainer
    depends_on:
    - traefik
    volumes:
    - ${CONFIG_PATH}/portainer/data:/data
    - ${CONFIG_PATH}/shared:/shared
    - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    command: -H unix:///var/run/docker.sock
    labels:
    - traefik.enable=true
    - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)
    - traefik.http.routers.portainer.entrypoints=websecure
    - traefik.http.routers.portainer.tls.certresolver=mydnschallenge
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: ${PUID}
    depends_on:
    - cadvisor
    - node-exporter
    volumes:
    - ${CONFIG_PATH}/prometheus:/prometheus
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
    - 9090:9090
    env_file: .env
    command:
    - --config.file=/etc/prometheus/prometheus.yml
  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbt
    privileged: true
    depends_on:
    - traefik
    volumes:
    - ${CONFIG_PATH}/qbt:/config
    - ${DL_PATH}:/downloads
    - ${MEDIA_PATH}:/media
    ports:
    - 8181:8181
    - 8999:8999/tcp
    - 8999:8999/udp
    env_file: .env
    environment:
    - LAN_NETWORK=192.168.1.0/24
    - NAME_SERVERS=1.1.1.1,1.0.0.1
    - VPN_ENABLED=yes
    - WEBUI_PORT_ENV=8181
    labels:
    - traefik.enable=true
    - traefik.http.routers.qbt.rule=Host(`qbt.${DOMAIN}`)
    - traefik.http.routers.qbt.entrypoints=websecure
    - traefik.http.routers.qbt.tls.certresolver=mydnschallenge
    - traefik.http.services.qbt.loadbalancer.server.port=8181
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
    - jackett
    - qbittorrentvpn
    - traefik
    volumes:
    - ${CONFIG_PATH}/radarr:/config
    - ${MEDIA_PATH}movies:/movies
    - ${DL_PATH}:/downloads
    ports:
    - 7878:7878
    env_file: .env
    labels:
    - traefik.enable=true
    - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)
    - traefik.http.routers.radarr.entrypoints=websecure
    - traefik.http.routers.radarr.tls.certresolver=mydnschallenge
    - traefik.http.services.radarr.loadbalancer.server.port=7878
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
    - jackett
    - qbittorrentvpn
    - traefik
    volumes:
    - ${CONFIG_PATH}/sonarr:/config
    - ${DL_PATH}:/downloads
    - ${MEDIA_PATH}/shows:/tv
    ports:
    - 8989:8989
    env_file: .env
    labels:
    - traefik.enable=true
    - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)
    - traefik.http.routers.sonarr.entrypoints=websecure
    - traefik.http.routers.sonarr.tls.certresolver=mydnschallenge
    - traefik.http.services.sonarr.loadbalancer.server.port=8989
  speedtest:
    image: atribe/speedtest-for-influxdb-and-grafana:latest
    container_name: speedtest
    depends_on:
    - influxdb
    restart: unless-stopped
    volumes:
    - ./speedtest.ini:/src/config.ini:ro
    network_mode: host
    env_file: .env
  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    depends_on:
    - traefik
    volumes:
    - ${CONFIG_PATH}/tautulli:/config
    - ${CONFIG_PATH}/Library/Application\ Support/Plex\ Media\ Server/Logs
    ports:
    - 8180:8180
    env_file: .env
    labels:
    - traefik.enable=true
    - traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN}`)
    - traefik.http.routers.tautulli.entrypoints=websecure
    - traefik.http.routers.tautulli.tls.certresolver=mydnschallenge
    - traefik.http.services.tautulli.loadbalancer.server.port=8180
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
    - speedtest
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /sys:/rootfs/sys:ro
    - /proc:/rootfs/proc:ro
    - /etc:/rootfs/etc:ro
    network_mode: host
    env_file: .env
    environment:
    - HOST_PROC=/rootfs/proc
    - HOST_SYS=/rootfs/sys
    - HOST_ETC=/rootfs/etc
  traefik:
    image: traefik:v2.2
    container_name: traefik
    volumes:
    - ${CONFIG_PATH}/letsencrypt:/letsencrypt
    - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - 80:80
    - 443:443
    - 8080:8080
    env_file: .env
    environment:
    - CF_API_EMAIL=${EMAIL}
    - CF_API_KEY=${CF_API_KEY}
    command:
    - --api.insecure=true
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --entrypoints.web.address=:80
    - --entrypoints.websecure.address=:443
    - --certificatesresolvers.mydnschallenge.acme.dnschallenge=true
    - --certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=cloudflare
    - --certificatesresolvers.mydnschallenge.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
    - --certificatesresolvers.mydnschallenge.acme.email=${EMAIL}
    - --certificatesresolvers.mydnschallenge.acme.storage=/letsencrypt/acme.json
  varken:
    image: boerderij/varken:latest
    container_name: varken
    depends_on:
    - telegraf
    user: ${PUID}
    volumes:
    - ${CONFIG_PATH}/varken:/config
    network_mode: host
    env_file: .env
  whoami:
    image: containous/whoami
    container_name: whoami
    depends_on:
    - traefik
    env_file: .env
    labels:
    - traefik.enable=true
    - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)
    - traefik.http.routers.whoami.entrypoints=websecure
    - traefik.http.routers.whoami.tls.certresolver=mydnschallenge
