---
services:
  docker-socket-proxy:
    container_name: proxy
    environment:
      - CONTAINERS=1
      - POST=0
      - SERVICES=1
      - TASKS=1
    image: ghcr.io/tecnativa/docker-socket-proxy
    labels:
      - homepage.group=Networking
      - homepage.name=Docker Socket Proxy
      - homepage.icon=docker
      - homepage.href=https://github.com/Tecnativa/docker-socket-proxy
      - homepage.description=Restricted docker socket proxy
    ports:
      - 127.0.0.1:2375:2375
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  homepage:
    container_name: homepage
    env_file: .env
    image: ghcr.io/gethomepage/homepage
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`watchtower.${DOMAIN}`)
    ports:
      - 3001:3000
    restart: unless-stopped
    volumes:
      - /etc/watchtower/docker/homepage:/app/config
  jellyfin:
    container_name: jellyfin
    devices:
      - /dev/dri
    env_file: .env
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${DOMAIN}
    extra_hosts:
      - host.docker.internal:host-gateway
    hostname: jellyfin
    image: jellyfin/jellyfin
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin
      - homepage.href=https://jellyfin.${DOMAIN}
      - homepage.description=Alternative Media server
      - homepage.widget.type=jellyfin
      - homepage.widget.url=https://jellyfin.${DOMAIN}
      - homepage.widget.key=${JELLYFIN_API_KEY}
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=host(`jellyfin.${DOMAIN}`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/lib/watchtower/jellyfin:/config
      - ${MISC_PATH:-/var/lib/watchtower/misc}:/data/misc
      - ${MOVIES_PATH:-/var/lib/watchtower/movies}:/data/movies
      - ${TRANSCODE_PATH:-/dev/shm}:/transcode
      - ${TVSHOWS_PATH:-/var/lib/watchtower/tvshows}:/data/tvshows
  node-exporter:
    command: --path.rootfs=/host
    container_name: node-exporter
    hostname: node-exporter
    image: quay.io/prometheus/node-exporter
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
  plex:
    container_name: plex
    devices:
      - /dev/dri
    env_file: .env
    environment:
      - ADVERTISE_IP=http://${HOST_IP:?host ip required}:32400/
      - PLEX_CLAIM=${PLEX_CLAIM:-claim-1234}
      - PLEX_GID=${PGID:-1000}
      - PLEX_UID=${PUID:-1000}
      - UMASK_SET=022
      - VERSION=plexpass
    hostname: watchtower
    image: plexinc/pms-docker:plexpass
    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex
      - homepage.href=https://watchtower.${DOMAIN_EXT}
      - homepage.description=Media Server
      - homepage.widget.type=plex
      - homepage.widget.url=http://${HOST_IP}:32400
      - homepage.widget.key=${PLEX_API_KEY}
      - homepage.widget.fields=["streams", "movies", "tv", "albums"]
      - traefik.enable=true
      - traefik.http.routers.plex.rule=host(`plex.${DOMAIN}`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.services.plex.loadbalancer.server.url=http://127.0.0.1:32400
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH:-/var/lib/watchtower/plex}:/config
      - ${MISC_PATH:-/var/lib/watchtower/misc}:/data/misc
      - ${MOVIES_PATH:-/var/lib/watchtower/movies}:/data/movies
      - ${TRANSCODE_PATH:-/var/lib/watchtower/transcode}:/transcode
      - ${TVSHOWS_PATH:-/var/lib/watchtower/tvshows}:/data/tvshows
  traefik:
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN},*.${DOMAIN}
      - --log.level=DEBUG
      - --providers.docker.exposedbydefault=true
      - --providers.docker=true
      - --serverstransport.insecureskipverify=true
    container_name: traefik
    env_file: .env
    extra_hosts:
      - host.docker.internal:172.17.0.1
    hostname: traefik
    image: traefik
    labels:
      - homepage.group=Networking
      - homepage.name=Traefik
      - homepage.icon=traefik
      - homepage.href=https://traefik.${DOMAIN}
      - homepage.description=Reverser Proxy
      - homepage.widget.type=traefik
      - homepage.widget.url=http://traefik:8080
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.service=api@internal
    networks:
      default: {}
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    restart: unless-stopped
    volumes:
      - /var/lib/watchtower/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  watchtower:
    container_name: watchtower
    env_file: .env
    environment:
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
