---
services:
  plex:
    container_name: plex
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    # devices:
    # - /dev/dri
    env_file: .env
    environment:
      - ADVERTISE_IP=http://${HOST_IP:?host ip required}:32400/
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - PLEX_CLAIM=${PLEX_CLAIM:-claim-1234}
      - PLEX_GID=${PGID:-1000}
      - PLEX_UID=${PUID:-1000}
      - UMASK_SET=022
      - VERSION=plexpass
    hostname: watchtower
    image: plexinc/pms-docker:plexpass
    network_mode: host
    runtime: nvidia
    volumes:
      - ${CONFIG_PATH:-/var/lib/watchtower/plex}:/config
      - ${MISC_PATH:-/var/lib/watchtower/misc}:/data/misc
      - ${MOVIES_PATH:-/var/lib/watchtower/movies}:/data/movies
      - ${TRANSCODE_PATH:-/dev/shm}:/transcode
      - ${TVSHOWS_PATH:-/var/lib/watchtower/tvshows}:/data/tvshows
  watchtower:
    container_name: watchtower
    env_file: .env
    environment:
      WATCHTOWER_SCHEDULE: "0 0 1 * * *"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
...