version: "3"
networks:
  web:
    external: true
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
    - /config/jackett:/config
    - /downloads:/downloads
    networks:
    - web
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:jackett.${DOMAIN}"
    - "traefik.port=9117"
  plex:
    image: linuxserver/plex
    container_name: plex
    devices:
    - /dev/dri:/dev/dri
    volumes:
    - /config/plex:/config
    - /movies:/data/movies
    - /tv:/data/tvshows
    network_mode: host
    expose:
    - 32400
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    - VERSION=docker
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /config/portainer/data:/data
    - /config/shared:/shared
    networks:
    - web
    environment:
    - TZ=${TZ}
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:portainer.${DOMAIN}"
    - "traefik.port=9000"
  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbt
    privileged: true
    volumes:
    - /config/qbt:/config
    - /downloads:/downloads
    networks:
    - web
    ports:
    - 8181:8181
    - 8999:8999
    - 8999:8999/udp
    environment:
    - LAN_NETWORK=192.168.1.0/24
    - NAME_SERVERS=8.8.8.8,8.8.4.4
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    - VPN_ENABLED=yes
    - WEBUI_PORT=8181
    - WEBUI_PORT_ENV=8181
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:qbt.${DOMAIN}"
    - "traefik.port=8181"
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
    - /config/sonarr:/config
    - /downloads:/downloads
    - /tv:/tv
    networks:
    - web
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:sonarr.${DOMAIN}"
    - "traefik.port=8989"
  traefik:
    image: traefik:1.7.2-alpine
    container_name: traefik
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /config/traefik/traefik.toml:/traefik.toml
    - /config/traefik/acme.json:/acme.json
    networks:
    - web
    ports:
    - 443:443
    - 80:80
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:traefik.${DOMAIN}"
    - "traefik.port=8080"
  whoami:
    image: containous/whoami
    container_name: "whoami"
    networks:
    - web
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:whoami.${DOMAIN}"
