version: "3.3"
services:
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
    - 9093:9093
    env_file: .env
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    ports:
    - 9999:9999
    env_file: .env
    command: --port 9999
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
    - prometheus
    - traefik
    user: ${PUID}
    volumes:
    - ${CONFIG_PATH}/grafana:/var/lib/grafana
    - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
    - 3000:3000
    env_file: .env
    environment:
    - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel
    labels:
    - traefik.enable=true
    - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)
    - traefik.http.routers.grafana.tls.certresolver=mydnschallenge
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
    - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    - ${CONFIG_PATH}/influxdb/db:/var/lib/influxdb
    ports:
    - 8086:8086
    - 8089:8089/udp
    env_file: .env
    environment:
    - INFLUXDB_HTTP_ENABLED=true
    - INFLUXDB_DB=host
    command: -config /etc/influxdb/influxdb.conf
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    depends_on:
    - traefik
    volumes:
    - ${CONFIG_PATH}/jackett:/config
    - ${DL_PATH}:/downloads
    ports:
    - 9117:9117
    env_file: .env
    labels:
    - traefik.enable=true
    - traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN}`)
    - traefik.http.routers.jackett.tls.certresolver=mydnschallenge
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    depends_on:
    - traefik
    volumes:
    - ${CONFIG_PATH}/lidarr:/config
    - ${DL_PATH}:/downloads
    - ${MEDIA_PATH}/music:/music
    ports:
    - 8686:8686
    env_file: .env
    labels:
    - traefik.enable=true
    - traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN}`)
    - traefik.http.routers.lidarr.tls.certresolver=mydnschallenge
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    pid: host
    volumes:
    - /:/host:ro,rslave
    ports:
    - 9100:9100
    env_file: .env
    command:
    - --path.rootfs=/host
    - --collector.filesystem.ignored-mount-points
    - ^/(sys|proc|dev/shm|run|host|etc|boot|var/lib/docker)
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    env_file: .env
    volumes:
    - ${CONFIG_PATH}/ombi:/config
    labels:
    - traefik.enable=true
    - traefik.http.routers.ombi.rule=Host(`ombi.${DOMAIN}`)
    - traefik.http.routers.ombi.tls.certresolver=mydnschallenge
  plex:
    image: plexinc/pms-docker
    container_name: plex
    hostname: watchtower
    depends_on:
    - traefik
    devices:
    - /dev/dri:/dev/dri
    volumes:
    - ${CONFIG_PATH}/plex:/config
    - /var/lib/plex/data:/data
    - /var/lib/plex/transcode:/transcode
    - ${MEDIA_PATH}/movies:/data/movies
    - ${MEDIA_PATH}/shows:/data/tvshows
    env_file: .env
    environment:
    - ADVERTISE_IP=http://${HOST_IP}:32400/
    - ALLOWED_NETWORK=${LAN_NETWORK},${DOCKER_NETWORK}
    - PLEX_CLAIM=${PLEX_CLAIM}
    - PLEX_GID=${PGID}
    - PLEX_UID=${PUID}
    - UMASK_SET=022
    - VERSION=docker
    ports:
    - 32400:32400
    - 3005:3005
    - 8324:8324
    - 32469:32469
    - 1900:1900/udp
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
    labels:
    - traefik.enable=true
    - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)
    - traefik.http.routers.plex.tls.certresolver=mydnschallenge
    - traefik.http.services.plex.loadbalancer.server.port=32400
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    depends_on:
    - traefik
    volumes:
    - ${CONFIG_PATH}/portainer/data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    command: -H unix:///var/run/docker.sock
    labels:
    - traefik.enable=true
    - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)
    - traefik.http.routers.portainer.tls.certresolver=mydnschallenge
    - traefik.http.services.portainer.loadbalancer.server.port=9000
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: ${PUID}
    depends_on:
    - cadvisor
    - node-exporter
    volumes:
    - ${CONFIG_PATH}/prometheus:/prometheus
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
    - 9090:9090
    env_file: .env
    command:
    - --config.file=/etc/prometheus/prometheus.yml
  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true
    depends_on:
    - traefik
    volumes:
    - ${CONFIG_PATH}/qbittorrentvpn:/config
    - ${DL_PATH}:/downloads
    - ${MEDIA_PATH}:/media
    ports:
    - 8181:8181
    - 8999:8999
    - 8999:8999/udp
    env_file: .env
    environment:
    - LAN_NETWORK=${LAN_NETWORK}
    - NAME_SERVERS=${NAME_SERVERS}
    - VPN_ENABLED=yes
    - WEBUI_PORT_ENV=8181
    labels:
    - traefik.enable=true
    - traefik.http.routers.qbittorrentvpn.rule=Host(`qbt.${DOMAIN}`)
    - traefik.http.routers.qbittorrentvpn.tls.certresolver=mydnschallenge
    - traefik.http.services.qbittorrentvpn.loadbalancer.server.port=8181
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
    - jackett
    - qbittorrentvpn
    - traefik
    volumes:
    - ${CONFIG_PATH}/radarr:/config
    - ${MEDIA_PATH}/movies:/movies
    - ${DL_PATH}:/downloads
    ports:
    - 7878:7878
    env_file: .env
    labels:
    - traefik.enable=true
    - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)
    - traefik.http.routers.radarr.tls.certresolver=mydnschallenge
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
    - jackett
    - qbittorrentvpn
    - traefik
    volumes:
    - ${CONFIG_PATH}/sonarr:/config
    - ${DL_PATH}:/downloads
    - ${MEDIA_PATH}/shows:/tv
    ports:
    - 8989:8989
    env_file: .env
    labels:
    - traefik.enable=true
    - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)
    - traefik.http.routers.sonarr.tls.certresolver=mydnschallenge
  speedtest:
    image: atribe/speedtest-for-influxdb-and-grafana
    container_name: speedtest
    depends_on:
    - influxdb
    restart: unless-stopped
    volumes:
    - ./speedtest.ini:/src/config.ini:ro
    network_mode: host
    env_file: .env
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    depends_on:
    - traefik
    volumes:
    - ${CONFIG_PATH}/tautulli:/config
    - ${CONFIG_PATH}/Library/Application\ Support/Plex\ Media\ Server/Logs
    ports:
    - 8180:8181
    env_file: .env
    labels:
    - traefik.enable=true
    - traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN}`)
    - traefik.http.routers.tautulli.tls.certresolver=mydnschallenge
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
    - speedtest
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /sys:/rootfs/sys:ro
    - /proc:/rootfs/proc:ro
    - /etc:/rootfs/etc:ro
    network_mode: host
    env_file: .env
    environment:
    - HOST_PROC=/rootfs/proc
    - HOST_SYS=/rootfs/sys
    - HOST_ETC=/rootfs/etc
  traefik:
    image: traefik:v2.2
    container_name: traefik
    volumes:
    - ${CONFIG_PATH}/letsencrypt:/letsencrypt
    - ./traefik.toml:/traefik.toml
    - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - 80:80
    - 443:443
    - 8080:8080
    env_file: .env
    environment:
    - CF_API_EMAIL=${EMAIL}
    - CF_API_KEY=${CF_API_KEY}
    - TRAEFIK_CERTIFICATESRESOLVERS_MYDNSCHALLENGE_ACME_EMAIL=${EMAIL}
  varken:
    image: boerderij/varken
    container_name: varken
    depends_on:
    - influxdb
    - telegraf
    user: ${PUID}
    volumes:
    - ${CONFIG_PATH}/varken:/config
    network_mode: host
    env_file: .env
  whoami:
    image: containous/whoami
    container_name: whoami
    depends_on:
    - traefik
    env_file: .env
    labels:
    - traefik.enable=true
    - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)
    - traefik.http.routers.whoami.tls.certresolver=mydnschallenge
