version: "3"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
    - ${CONFIG_PATH}/jackett:/config
    - ${MEDIA_PATH}/downloads:/downloads
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:jackett.${DOMAIN}"
    - "traefik.port=9117"
  plex:
    image: plexinc/pms-docker
    container_name: plex
    devices:
    - /dev/dri:/dev/dri
    hostname: plex.${DOMAIN}
    restart: unless-stopped
    network_mode: host
    volumes:
    - ${CONFIG_PATH}/plex:/config
    - ${PLEX_PATH}/data:/data
    - ${PLEX_PATH}/transcode:/transcode
    - ${MEDIA_PATH}/movies:/data/movies
    - ${MEDIA_PATH}/shows:/data/tvshows
    environment:
    - PLEX_GID=${PGID}
    - PLEX_UID=${PUID}
    - TZ="${TZ}"
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:watchtower.${DOMAIN}"
    - "traefik.port=32400"
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
    - ${CONFIG_PATH}/portainer/data:/data
    - ${CONFIG_PATH}/shared:/shared
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - TZ=${TZ}
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:portainer.${DOMAIN}"
    - "traefik.port=9000"
  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbt
    privileged: true
    ports:
    - 8181:8181
    volumes:
    - ${CONFIG_PATH}/qbt:/config
    - ${MEDIA_PATH}/downloads:/downloads
    environment:
    - LAN_NETWORK=192.168.1.0/24
    - NAME_SERVERS=8.8.8.8,8.8.4.4
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    - VPN_ENABLED=yes
    - WEBUI_PORT=8181
    - WEBUI_PORT_ENV=8181
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:qbt.${DOMAIN}"
    - "traefik.port=8181"
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
    - 7878:7878
    volumes:
    - ${CONFIG_PATH}/config:/config
    - ${MEDIA_PATH}/movies:/movies
    - ${MEDIA_PATH}/downloads:/downloads
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:radarr.${DOMAIN}"
    - "traefik.port=7878"
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
    - ${CONFIG_PATH}/sonarr:/config
    - ${MEDIA_PATH}/downloads:/downloads
    - ${MEDIA_PATH}/shows:/tv
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:sonarr.${DOMAIN}"
    - "traefik.port=8989"
  traefik:
    image: traefik:1.7.16
    container_name: traefik
    volumes:
    - ${CONFIG_PATH}/traefik/fullchain.pem:/cert.pem
    - ${CONFIG_PATH}/traefik/privkey.pem:/privkey.pem
    - ${CONFIG_PATH}/traefik/traefik.toml:/traefik.toml
    - /var/run/docker.sock:/var/run/docker.sock
    command: --web
    network_mode: host
    ports:
    - 443:443
    - 80:80
    labels:
    - "traefik.backend=web"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:traefik.${DOMAIN}"
    - "traefik.port=8080"
  whoami:
    image: containous/whoami
    container_name: "whoami"
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:whoami.${DOMAIN}"
