rule_files:
  - 'alert.rules'

scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:9999
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - prometheus:9090
- job_name: node-exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - node-exporter:9100
- job_name: alertmanager
  scrape_interval: 5s
  static_configs:
  - targets:
    - alertmanager:9093

