defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.dashboard]
  address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
      usersFile = "/.htpasswd"
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    certFile = "/cert.pem"
    keyFile = "/privkey.pem"

[api]
entrypoint = "dashboard"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
